In [12]:
import tensorflow as tf

def run():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)
    
    # Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)    
    
    with tf.Session() as sess:
        pass
        # Feed in the logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})

    print(output)
    
    return output

In [13]:
### DON'T MODIFY ANYTHING BELOW ###
### Be sure to run all cells above before running this cell ###
import grader

try:
    grader.run_grader(run)
except Exception as err:
    print(str(err))

[0.6590012  0.24243298 0.09856589]
That's the correct softmax!




In [ ]:
[0.6590012  0.24243298 0.09856589]
[0.36605948 0.33122432 0.30271623]